services:
  transport-db:
    build: .
    container_name: transport-db
    environment:
      POSTGRES_DB: transport_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transport-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d transport_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:9.5.0
    container_name: transport-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - transport-network
    restart: unless-stopped
    depends_on:
      - transport-db

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  transport-network:
    driver: bridge
